### ISSUE TITLE
Unrecognized import path

### ISSUE THREAD

**Issue by duraki** [sradley/overflow#1]
```
$ go get github.com/sradley/overflow
package overflow/cmd: unrecognized import path "overflow/cmd": import path does not begin with hostname
```

**Comment by sradley** [comment]
Ah looks like an issue with go modules. I'll push a fix soon.

**Comment by sradley** [comment]
Done, `go get` will work now.

**Comment by duraki** [comment]
I don't want to open a new issue; can confirm it's fixed.

Now you are missing PE in `/bin`. I guess some sort of wrapper is needed for the go binary?

**Comment by sradley** [comment]
I'll re-open this issue. What error message are you getting?

**Comment by sradley** [comment]
Also, if you can try and build it from the installation directory.
```
$ cd go/src/github.com/sradley/overflow
$ go build
```

Let me know if you get any errors.

**Comment by duraki** [comment]
I'm running MacOS Mojave.

Yes, that works. But afaik `overflow` binary should be in PATH, no? 

```
$ pwd
/Users/me/go/src/github.com/sradley/overflow
$ file overflow
overflow: Mach-O 64-bit executable x86_64
```

**Comment by sradley** [comment]
Yeah, `go get github.com/sradley/overflow` should be installing the binary inside `go/bin/`. 

Does `$ go install` work when you're inside the installation directory?

**Comment by duraki** [comment]
Yes;

`$ go install` works and puts `overflow` binary to `GOPATH/bin`. Be with me, it's a fresh MacOS install and first Go tool I'm installing. I will try `amass` or something to confirm it's not up to me.

**Comment by sradley** [comment]
Take a look at the output `go env`, maybe there's a weird flag set.

**Comment by sradley** [comment]
Hey, I'm gonna close this since I'm unable to reproduce this error.
